import type { NextConfig } from "next";

const isDevelopment = process.env.NODE_ENV === "development";
const supabaseOrigin = (() => {
  try {
    return new URL(process.env.NEXT_PUBLIC_SUPABASE_URL ?? "").origin;
  } catch {
    return "";
  }
})();
const supabaseConnections = (() => {
  if (!supabaseOrigin) return "";
  const websocket = new URL(supabaseOrigin);
  websocket.protocol = websocket.protocol === "https:" ? "wss:" : "ws:";
  return `${supabaseOrigin} ${websocket.origin}`;
})();
const contentSecurityPolicy = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${isDevelopment ? " 'unsafe-eval'" : ""}`,
  "style-src 'self' 'unsafe-inline'",
  // Photos live in a private Supabase Storage bucket and are shown through
  // signed URLs on the Supabase origin, so that origin has to be allowed here
  // or every image is blocked. Same host already trusted by `connect-src`; no
  // wildcard and no third party is introduced.
  `img-src 'self' data: blob: ${supabaseOrigin}`.trim(),
  "font-src 'self' data:",
  `connect-src 'self' ${supabaseConnections}${isDevelopment ? " ws:" : ""}`.trim(),
  "object-src 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "frame-src 'none'",
  "frame-ancestors 'none'",
  "worker-src 'self' blob:",
  ...(!isDevelopment ? ["upgrade-insecure-requests"] : []),
].join("; ");

const nextConfig: NextConfig = {
  // Development only; `next build` and `next start` never read this. The dev
  // server binds 0.0.0.0, so Next auto-allows "0.0.0.0" rather than the LAN
  // address a phone actually connects to, which blocks HMR and the error
  // overlay for on-device testing.
  allowedDevOrigins: ["localhost", "192.168.0.11"],

  async headers() {
    return [
      {
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: contentSecurityPolicy },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=()" },
        ],
      },
      {
        /**
         * Documents must always be revalidated before they are reused.
         *
         * Without this the platform's own `s-maxage=31536000` is the only
         * freshness signal on an HTML response, and a private cache that
         * chooses to apply a heuristic lifetime can pin a document for a long
         * time. In a browser tab that is survivable — the user can pull to
         * refresh. An installed PWA has no address bar, no reload button and
         * no pull-to-refresh, so a pinned document leaves that user on an old
         * build with no way out. `no-cache` still allows the copy to be
         * stored; it just forces the conditional request, which the ETag
         * answers with a 304, so the cost is one small round trip.
         *
         * `_next/static` and `_next/image` are excluded: those URLs are
         * content-hashed (verified — changing a stylesheet changes its chunk
         * filename) and must keep the immutable lifetime from
         * `public/_headers`, or every navigation would refetch the bundle.
         * `/api/` is excluded so nothing here can weaken a route that sets its
         * own caching for authenticated data.
         */
        source: "/((?!_next/static|_next/image|api/).*)",
        headers: [{ key: "Cache-Control", value: "no-cache" }],
      },
      {
        // Parity only. In production Cloudflare serves `public/` directly and
        // this block never runs — `public/_headers` is authoritative there and
        // carries the same rules. Keeping them here means `next start` and a
        // local production check behave like the deployment.
        source: "/sw.js",
        headers: [
          { key: "Cache-Control", value: "no-cache, no-store, must-revalidate" },
          { key: "Content-Type", value: "application/javascript; charset=utf-8" },
          { key: "Content-Security-Policy", value: "default-src 'self'; script-src 'self'" },
        ],
      },
      {
        // The mirror image: `manifest.webmanifest` is generated by
        // `app/manifest.ts`, so it is served by the Next worker and NOT by
        // Cloudflare's asset handler — `public/_headers` cannot match it, and
        // this is the only place its caching can be set.
        source: "/manifest.webmanifest",
        headers: [{ key: "Cache-Control", value: "public, max-age=0, must-revalidate" }],
      },
    ];
  },
};

export default nextConfig;
