import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";

/**
 * The dashboard card must agree with the screen it opens.
 *
 * WHY THIS FILE EXISTS
 *   Checkpoint 2 added a second place that reports an event's spend. Two places
 *   computing the same figure is exactly how they end up disagreeing, and a
 *   card that overstates what an event has cost is worse than a card with no
 *   figure at all.
 *
 * NO MAGIC EXPECTED VALUES
 *   Nothing here asserts a particular number of pounds. Every figure is
 *   GENERATED by a seeded pseudo-random fixture and the assertions are
 *   relational: dashboard equals Event Home, event A is unaffected by event B,
 *   a voided purchase counts for nothing, an archived recipient counts for
 *   nothing. The fixture is re-generated across many seeds, so the properties
 *   hold for whatever the live figures happen to be rather than for one
 *   snapshot of them.
 *
 *   In particular: no value in this repository asserts what Christmas 2026 has
 *   actually cost. That is live data, and only the database knows it.
 */

const root = process.cwd();
// Line endings are normalised on the way in. Git stores LF and checks files out
// as CRLF on Windows, so a multi-line pattern written with \n silently stops
// matching a file nobody has edited -- a false failure about the product,
// caused by a checkout setting.
const read = (...parts) => readFileSync(join(root, ...parts), "utf8").replace(/\r\n/gu, "\n");

// ---------------------------------------------------------------------------
// A seeded generator, so a failure is reproducible and no constant is magic
// ---------------------------------------------------------------------------

function makeRandom(seed) {
  let state = seed >>> 0;
  return () => {
    // xorshift32 — small, deterministic, and good enough to shuffle pennies.
    state ^= state << 13; state >>>= 0;
    state ^= state >> 17;
    state ^= state << 5; state >>>= 0;
    return state / 0x1_0000_0000;
  };
}

/**
 * Two events, each with active and archived recipients, live and voided
 * purchases. Amounts and counts all come from the seed.
 */
function generateFamily(seed) {
  const random = makeRandom(seed);
  const between = (low, high) => low + Math.floor(random() * (high - low + 1));

  const events = ["event-a", "event-b"];
  const recipients = [];
  const purchases = [];

  for (const eventId of events) {
    const recipientCount = between(2, 5);
    for (let index = 0; index < recipientCount; index += 1) {
      const recipientId = `${eventId}-recipient-${index}`;
      // At least one archived recipient per event once the count allows it:
      // this is the case that made the dashboard and Event Home disagree.
      const active = index === 0 ? true : between(0, 3) > 0;
      recipients.push({
        id: recipientId,
        christmas_event_id: eventId,
        budget_pennies: between(0, 20_000),
        active,
      });

      for (let purchase = 0; purchase < between(0, 4); purchase += 1) {
        const voided = between(0, 3) === 0;
        purchases.push({
          id: `${recipientId}-purchase-${purchase}`,
          christmas_recipient_id: recipientId,
          actual_price_pennies: between(1, 12_000),
          deleted_at: voided ? "2026-11-11T10:00:00Z" : null,
        });
      }
    }
  }

  return { events, recipients, purchases };
}

// ---------------------------------------------------------------------------
// The two code paths, each mirroring one real implementation
// ---------------------------------------------------------------------------

/**
 * `listEvents` in src/utils/supabase/events-server.ts.
 *
 * Active recipients of the event; live purchases belonging to those recipients.
 */
function dashboardCard(family, eventId) {
  const recipients = family.recipients.filter((row) => row.active);
  const eventByRecipient = new Map(recipients.map((row) => [row.id, row.christmas_event_id]));

  let budgetPennies = 0;
  for (const row of recipients) {
    if (row.christmas_event_id === eventId) budgetPennies += row.budget_pennies;
  }

  let spentPennies = 0;
  for (const purchase of family.purchases) {
    if (purchase.deleted_at !== null) continue;
    if (eventByRecipient.get(purchase.christmas_recipient_id) !== eventId) continue;
    spentPennies += purchase.actual_price_pennies;
  }

  return { budgetPennies, spentPennies };
}

/**
 * Event Home: `FamilyProvider` loads this event's recipients with their live
 * purchase totals, and `useTotals` sums the active ones.
 */
function eventHomeTotals(family, eventId) {
  const recipients = family.recipients.filter((row) => row.christmas_event_id === eventId);

  const spentByRecipient = new Map();
  for (const purchase of family.purchases) {
    if (purchase.deleted_at !== null) continue;
    if (!recipients.some((row) => row.id === purchase.christmas_recipient_id)) continue;
    spentByRecipient.set(
      purchase.christmas_recipient_id,
      (spentByRecipient.get(purchase.christmas_recipient_id) ?? 0) + purchase.actual_price_pennies,
    );
  }

  const people = recipients.map((row) => ({
    active: row.active,
    budgetPennies: row.budget_pennies,
    spentPennies: spentByRecipient.get(row.id) ?? 0,
  }));

  const active = people.filter((person) => person.active);
  return {
    budgetPennies: active.reduce((sum, person) => sum + person.budgetPennies, 0),
    spentPennies: active.reduce((sum, person) => sum + person.spentPennies, 0),
  };
}

// ---------------------------------------------------------------------------
// The properties
// ---------------------------------------------------------------------------

const SEEDS = Array.from({ length: 200 }, (_, index) => index * 2_654_435_761 + 12_345);

test("dashboard spend equals Event Home spend, for both events, at every seed", () => {
  for (const seed of SEEDS) {
    const family = generateFamily(seed);
    for (const eventId of family.events) {
      const card = dashboardCard(family, eventId);
      const home = eventHomeTotals(family, eventId);
      assert.equal(card.spentPennies, home.spentPennies, `spend disagreed for ${eventId} at seed ${seed}`);
      assert.equal(card.budgetPennies, home.budgetPennies, `budget disagreed for ${eventId} at seed ${seed}`);
    }
  }
});

test("the fixture really does exercise the cases that matter", () => {
  // A property test that never hits the interesting rows proves nothing, so
  // assert the generator produces them.
  let archivedWithPurchases = 0;
  let voided = 0;
  let live = 0;
  for (const seed of SEEDS) {
    const family = generateFamily(seed);
    const archived = new Set(family.recipients.filter((row) => !row.active).map((row) => row.id));
    for (const purchase of family.purchases) {
      if (purchase.deleted_at === null) live += 1; else voided += 1;
      if (archived.has(purchase.christmas_recipient_id) && purchase.deleted_at === null) archivedWithPurchases += 1;
    }
  }
  assert.ok(live > 0, "the fixture must contain live purchases");
  assert.ok(voided > 0, "the fixture must contain voided purchases");
  assert.ok(
    archivedWithPurchases > 0,
    "the fixture must contain live purchases for archived recipients — the case that broke the card",
  );
});

test("a second event's purchases never move the first event's card", () => {
  for (const seed of SEEDS.slice(0, 50)) {
    const family = generateFamily(seed);
    const before = dashboardCard(family, "event-a");

    // Everything about event B changes: more recipients, more money.
    const extended = {
      ...family,
      recipients: [
        ...family.recipients,
        { id: "event-b-extra", christmas_event_id: "event-b", budget_pennies: 999_99, active: true },
      ],
      purchases: [
        ...family.purchases,
        { id: "event-b-extra-purchase", christmas_recipient_id: "event-b-extra", actual_price_pennies: 4_242, deleted_at: null },
      ],
    };

    const after = dashboardCard(extended, "event-a");
    assert.deepEqual(after, before, `event B contaminated event A at seed ${seed}`);
    assert.notDeepEqual(
      dashboardCard(extended, "event-b"),
      dashboardCard(family, "event-b"),
      "the change must actually have landed on event B",
    );
  }
});

test("a voided purchase contributes nothing, and archiving a recipient removes their spend from both", () => {
  const family = generateFamily(7);
  const target = family.recipients.find((row) => row.active && row.christmas_event_id === "event-a");
  assert.ok(target);

  // Adding a VOIDED purchase changes neither figure.
  const withVoided = {
    ...family,
    purchases: [...family.purchases, {
      id: "voided-extra",
      christmas_recipient_id: target.id,
      actual_price_pennies: 5_555,
      deleted_at: "2026-12-01T00:00:00Z",
    }],
  };
  assert.deepEqual(dashboardCard(withVoided, "event-a"), dashboardCard(family, "event-a"));
  assert.deepEqual(eventHomeTotals(withVoided, "event-a"), eventHomeTotals(family, "event-a"));

  // Adding a LIVE purchase moves both by exactly the same amount.
  const withLive = {
    ...family,
    purchases: [...family.purchases, {
      id: "live-extra",
      christmas_recipient_id: target.id,
      actual_price_pennies: 5_555,
      deleted_at: null,
    }],
  };
  assert.equal(
    dashboardCard(withLive, "event-a").spentPennies - dashboardCard(family, "event-a").spentPennies,
    5_555,
  );
  assert.equal(
    eventHomeTotals(withLive, "event-a").spentPennies - eventHomeTotals(family, "event-a").spentPennies,
    5_555,
  );

  // Archiving that recipient removes their spend from BOTH, together.
  const archived = {
    ...withLive,
    recipients: withLive.recipients.map((row) => (row.id === target.id ? { ...row, active: false } : row)),
  };
  assert.deepEqual(dashboardCard(archived, "event-a"), eventHomeTotals(archived, "event-a"));
});

// ---------------------------------------------------------------------------
// The models above must keep matching the real source
// ---------------------------------------------------------------------------

test("both real implementations still carry the rule these models encode", () => {
  const server = read("src", "utils", "supabase", "events-server.ts");
  // Active recipients only, live purchases only, integer pennies.
  assert.match(server, /\.filter\(\(row\) => row\.active\)/, "the dashboard must drop archived recipients");
  assert.match(server, /\.is\("deleted_at", null\)/, "the dashboard must drop voided purchases");
  assert.match(server, /actual_price_pennies/);
  assert.doesNotMatch(server, /Math\.round|toFixed|parseFloat/, "pennies stay integers");
  // And it says out loud that it has to agree with Event Home.
  assert.match(server, /THE CARD MUST AGREE WITH THE SCREEN IT OPENS/);

  const familyContext = read("src", "app", "family-context.tsx");
  assert.match(familyContext, /\.is\("deleted_at", null\)/, "Event Home must drop voided purchases");
  assert.match(
    familyContext,
    /const active = people\.filter\(\(person\) => person\.active\)/,
    "useTotals must sum active recipients only",
  );

  // Neither path invents a figure: no financial engine is involved in either.
  for (const source of [server, read("src", "app", "events-dashboard.tsx")]) {
    assert.doesNotMatch(source, /calculateNetOwedBalances|splitEvenly|responsibility/i);
  }
});

test("no test or screen asserts what Christmas has actually cost", () => {
  // The £95 in the Checkpoint 1 preflight was a value invented for a disposable
  // in-memory fixture. It is not, and must never become, an expectation about
  // the live database.
  const dashboard = read("src", "app", "events-dashboard.tsx");
  const server = read("src", "utils", "supabase", "events-server.ts");
  for (const source of [dashboard, server]) {
    assert.doesNotMatch(source, /\b9500\b|\b9_500\b|£95\b/, "no fixture figure may appear in application code");
  }

  // Where fixture figures DO appear, they are invented inside the file that
  // asserts them — a closed loop, not a reading taken from the live database.
  const scoping = read("scripts", "event-scoping.test.mjs");
  assert.match(scoping, /9_500/, "the Checkpoint 1 suite does assert its own totals");
  assert.match(
    scoping,
    /INVENTED, NOT OBSERVED/,
    "and it must say plainly that those totals are invented",
  );
  assert.match(scoping, /familyFixture\(\)/, "its figures come from a fixture defined in the same file");

  // Nothing in this suite states an expected pound value at all: every
  // assertion above is relational.
  const self = read("scripts", "event-dashboard-consistency.test.mjs");
  // Only positive expectations count: a `doesNotMatch` guard naturally names
  // the figure it is banning.
  const expectations = self.split("\n").filter((line) => /assert\.(equal|deepEqual|match)\b/u.test(line));
  assert.ok(expectations.length > 0);
  assert.equal(
    expectations.filter((line) => /£/u.test(line)).length,
    0,
    "this suite must not assert a pound figure",
  );
});
